[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=15
compiler.cppstd=gnu23
compiler.libcxx=libstdc++11
build_type=Release

[buildenv]
#PATH=/opt/x86_64-pc-linux-musl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CONAN_CMAKE_FIND_ROOT_PATH=/opt/x86_64-pc-linux-musl/x86_64-pc-linux-musl/sysroot
CONAN_CMAKE_SYSTEM_NAME=Linux
#LD_LIBRARY_PATH=/opt/x86_64-pc-linux-musl/x86_64-pc-linux-musl/sysroot/lib:/opt/x86_64-pc-linux-musl/x86_64-pc-linux-musl/lib64
CHOST=x86_64-pc-linux-musl
AR=x86_64-pc-linux-musl-ar
AS=x86_64-pc-linux-musl-as
RANLIB=x86_64-pc-linux-musl-ranlib
CC=x86_64-pc-linux-musl-gcc
CXX=x86_64-pc-linux-musl-g++
STRIP=x86_64-pc-linux-musl-strip
