set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR |ARCH|)

set(CMAKE_SYSROOT "%TOOLCHAIN_DIR%/${CMAKE_SYSTEM_PROCESSOR}-pc-linux-musl/sysroot")
set(CMAKE_STAGING_PREFIX "${CMAKE_BINARY_DIR}/stage")

set(CMAKE_C_COMPILER "%TOOLCHAIN_DIR%/bin/${CMAKE_SYSTEM_PROCESSOR}-pc-linux-musl-gcc")
set(CMAKE_CXX_COMPILER "%TOOLCHAIN_DIR%/bin/${CMAKE_SYSTEM_PROCESSOR}-pc-linux-musl-g++")

set(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
set(CMAKE_C_FLAGS "-static -static-libgcc")
set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} -static-libstdc++")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_CXX_FLAGS}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
