#!/bin/bash

if [ ! -d /proc/sys/fs/binfmt_misc ] ; then
	modprobe -q binfmt_misc
fi

if [ ! -d /proc/sys/fs/binfmt_misc ] ; then
	echo "You need support for 'misc binaries' in your kernel!"
	return
fi

if [ ! -f /proc/sys/fs/binfmt_misc/register ] ; then
	mount -t binfmt_misc -o nodev,noexec,nosuid \
		binfmt_misc /proc/sys/fs/binfmt_misc >/dev/null 2>&1
	echo $? || return
fi

if [ -f /proc/sys/fs/binfmt_misc/qemu-mips ] ; then
	echo -n "-1" > /proc/sys/fs/binfmt_misc/qemu-mips
fi

echo -n ':qemu-mips:M::\x7fELF\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x08\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00:\xff\xff\xff\xff\xff\xff\xff\x00\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x20:/usr/bin/qemu-mips:' >/proc/sys/fs/binfmt_misc/register
